language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install selenium
  - pip install pytest
  - pip install Appium-Python-Client
  - pip install sauceclient

env:
  global:
    - secure: QASPfyn01qwH7YKHs59rF7f8GZy3KiinN3+IXHks4Y6Dm4ESeRmsNwpYzZPEzY/jvYWxVSYk5Mo2lVJVX0dPJAdtFqCuwfHEPXMmNQ6grm9yLg0q229rPGob7D7PDNwA1VEHEmlyhtUR04hQBG3mZWnL4txOBXqF+MrXrRCtaIM=
    - secure: YjQo6p0nHvjqbOByxj34psB/YyGRfp68rXuF84319qiXmP5ILxt/1CJdERhoHfoE9ayPFh0LAFHIcC2G89X+pdtxQb+GPeLNCIIIQWRtyLxWRc/2FPXD4g2xKLHgQuBg+Yj2I4L1ZnybErrTXULHSrY8c3GWXuAFWQRlWZY3ijo=
    
# command to run tests
script: py.test testcases/test_facebook_login.py
