language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install selenium
  - pip install pytest
  - pip install Appium-Python-Client
  - pip install sauceclient

env:
  global:
    - secure: F1jovPALc664h97ZGvXOZ6oT3RON0+fuuEdWM88xx50Pb82TNWKl8szEdmZ96sRmw1LHzVtS5CVN3ugDpO3xCKxorckrtOXjzx9ffeUzwgEwnJXuNF91ew5N44h/Y3Zjw5XvF2opIaT9DMLIKWMAppNQY8Th+XMUFVRZmIaiNKA=
    - secure: kYW8g4+jImHgltsD+TUn1Cu5pylKPo5tvUKtfD6w3uQLiMU6gj3h9tqVOejGW1CMgGTHrg0vdi6PyOJLC+D0ri0XhyWP28ecuyfNC2yi+v+UsnWEAnIRFzlCecV7hJkXJrxRbTVdmtU+H2PCBKlXmbHRiN83BI4LrAYxvv3tfss=

# command to run tests
script: py.test testcases/test_facebook_login.py
