language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install selenium
  - pip install pytest
  - pip install Appium-Python-Client


addons:
  sauce_connect: true

env:
  global:
    - secure: cjtanwHng8Fqa8anYoKjn07jgYd/VuLHOdPIxOmVkWB4926ikdXwKiAaXurHTXGK7R/RYOd/c+alaZ5jTyfS/4KpAbb2vj6jIiXoT2eJqIKaDPPd7T6vpGTOOxShqmsxM+d01dxNK0xAfpCZ4j19M3aKlr5EOXgklsyAuujNHX4=
    - secure: FxKPxI5NdrKhsLSDs+ltUfZ3DjxknsusZwqxUXZiNmbmAqkazSVCWjG+AiI24KS589Oz1FGhrn3PmayWnZ9o1DIjsYU9N6G+L9OpD1xmTaAFtM/LRz/6BUhaT47K3ABV4Jp/5Clo5iOOIXoGTTmH4XIv4krzeIoGRo3z72KUMc0=

# command to run tests
script: py.test testcases/test_facebook_login.py