language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install selenium
  - pip install pytest
  - pip install Appium-Python-Client
  - pip install sauceclient

env:
  global:
    - secure: asb8/zLS4PTFhOP5vq2eijiiuvl9nrc92OJ3viDgAQwvHKcL4D07+Y9TAjnBYsm7WKKDaCoOZN/Y6PQOdLJrbFE1HNQTHhYYhrTem7JnDfRZscMtGscjIVfTQrCboj+Ty5lKm3+4wzCynR1Z4tft1PiSFSHePznDb/a2JseAtEM=
    - secure: ZFnXsy574j/7zuyemFpjjS1MKp5cyn76cm+Md101Lih/Mjgr3xpSDiIETumq6qxBJEWF+rYOUSifKQs8IyN+9KcUb9bsB6IccN4jH9pRhvL+u2nrhCSERxVtwLZPwOFGLCdZ+ivv7JG5DbnRP3nS1y7aSiqmgvDAFr7FZp67LSo=

# command to run tests
script: py.test testcases/test_facebook_login.py
