language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install selenium
  - pip install pytest
  - pip install Appium-Python-Client
  - pip install sauceclient

env:
  global:
    - secure: E1gmPdLex6QKstkwjGEXs1/zjXUTNY7PJt9qNepCLl3B1n9jq0L5D2XNfPOLpNzGPweF85vJxyBQ5pQLxF7u6tQ1oPVjmZmz9V1pRXpZmttf4hbCqJk3Yw2qY2sNKNfALW4YSvDWCS/jIARbHqYhWOQYUkcoOYSsQsDuwfCbDAg=
    - secure: h63VBqN55WVLLmUC4/HIKGflUwwfcOOyGrsEy+2Ds8KKcTpyjCaYqZOgcg4jNyXTj2E3kR9Qpv3z5AcnZvRKpGNMaq/6UqPcxBqROG9ZYbfrWAt9EY5y14lpvfvXUm+8P8lJcJEZceaN2Dkq1dW+aIAngPQ6StqT3ciTjHVChGE=
    
# command to run tests
script: py.test testcases/test_facebook_login.py
