language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install selenium
  - pip install pytest
  - pip install Appium-Python-Client
  - pip install sauceclient


addons:
  sauce_connect: false

env:
  global:
    - secure: Lxl9sOAmdL6rWbzuI0ncqf+nsFHkjdO0QCRBaquTt6RLiij50cHs5SqTYW7GzzxcfOe6ZOeJwh+sHQvlFkpZLzxnKvQHXFRFpXR4VCTZhp3rnPhzBR5spyL4ewijm9/DOj2TVEL2QDUUq3rX32GOyVh52/aaoc3Bxp38H6MMfrk=
    - secure: JyehUVUmuEZCuIz8S4+vZ0QG0OuXHxpBuHHyQg2YwDUljSMMkRCsRUU3ggkmAnkPau9qGugfzlRx5mhnZMY29fsElzwAESecQ0wNtldgXcZ7B9heuQ9ivdLUwJdcR6Wk7yHYK1g8JmGduRRFHE63Hki5QwpLxz5DDqVV5fszY1A=
# command to run tests
script: py.test testcases/test_facebook_login.py